gitfeat: Setting-up-terraform-backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,6 +3,60 @@
 # Check https://circleci.com/docs/2.0/language-go/ for more details
 version: 2
 jobs:
+  plan-apply:
+    working_directory: /go/src/github.com/servian/TechChallengeApp
+    docker:
+      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
+    steps:
+      - checkout
+      - run:
+          name: terraform init & plan
+          command: |            
+            cd infrastructure
+            cat << EOF > variables.tfvars
+            AWS_REGION       = "ap-southeast-2"
+            TF_DBUSER       = "${TF_DBUSER}"
+            TF_DBPASSWORD    = "${TF_DBPASSWORD}"
+            TF_DBSUBNETGROUP = "dbsubnetgroup"
+            tag_prefix = "apptechc"
+            EOF
+            if [[ -f variables.tfvars ]]
+            then
+              echo "file is present"
+            else
+              echo "tfvar file missing!!!"
+              exit 1;
+            fi
+            cat variables.tfvars
+            terraform init -input=false
+            terraform plan -out tfapply -var-file variables.tfvars
+      - persist_to_workspace:
+          root: .
+          paths:
+            - .            
+  apply:
+    docker:
+      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
+    steps:
+      - attach_workspace:
+         at: .
+      - run:
+          name: terraform
+          command: |            
+            rm conf.toml 
+            cd infrastructure
+            terraform init -input=false
+            terraform plan -out tfapply -var-file variables.tfvars
+            terraform apply -auto-approve tfapply
+            cd ..
+            #cp ./infrastructure/conf.toml .  
+            #cp ./infrastructure/ecr_repourl.conf . 
+
+      - persist_to_workspace:
+          root: .
+          paths:
+            - .
+  
   build:
     working_directory: /go/src/github.com/servian/TechChallengeApp
     docker:
@@ -176,7 +230,17 @@ workflows:
   version: 2
   build_test_deploy:
     jobs:
-      - build
+      - plan-apply 
+      - hold-apply:
+          type: approval
+          requires:
+            - plan-apply
+      - apply:
+          requires:
+            - hold-apply 
+      - build:
+          requires: 
+            - apply
       - deploy:
           requires: 
             - build
